### ISSUE TITLE
Clean up HTTP Response Body

### ISSUE THREAD

**Issue by barrebre** [barrebre/goDynaPerfSignature#24]
On multiple metrics, a response looks like:
"Successful deploy! Performance improvement...
Threshold ..."

This isn't necessary clear to the user what it's reporting

**Comment by popecruzdt** [comment]
This would be a very welcomed enhancement!

Response body in JSON format with a standard response.  Such as, "result: xyz", "message": "some message", "details": [ array of each evaluation made during the performance signature ].

**Comment by barrebre** [comment]
Addressed with #59
